services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: datascientest
      POSTGRES_DB: france_emplois
    ports:
      - "5432:5432"
    networks:
      - container_network

  ubuntu:
    container_name: data_processing
    image: mooncak/adzuna_data_processing:test
    networks:
      - container_network

networks:
  container_network:
