services:
  extract:
    image: aurelclx/extract_france_travail
    volumes:
      - ${PWD}/data:/app/data

  transform:
    image: aurelclx/transform_france_travail
    volumes:
      - ${PWD}/data:/app/data
    depends_on:
      extract:
        condition: service_completed_successfully

  load:
    image: aurelclx/load_france_travail
    volumes:
      - ${PWD}/data:/app/data
    networks:
      - mon_reseau
    depends_on:
      transform:
        condition: service_completed_successfully


  database:
    image: aurelclx/database_france_travail
    container_name: aurelclx_villani
    networks:
      - mon_reseau

  api:
    image: aurelclx/api_france_travail
    ports:
      - "8000:8000"
    networks:
      - mon_reseau

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    networks:
      - mon_reseau


  postgresql-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgresql_exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:datascientest@aurelclx_villani/france_emplois?sslmode=disable"
    depends_on:
      - prometheus
      - database
    networks: 
      - mon_reseau
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    networks:
      - mon_reseau

volumes:
  prometheus:
  grafana:
  postgresql_exporter:

networks:
  mon_reseau:
    driver: bridge
