services:
  db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: datascientest
      POSTGRES_DB: france_emplois
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/data/france_travail_ressources/sql:/docker-entrypoint-initdb.d
    networks:
      - project_network

  api:
    container_name: api
    image: api:v1
    ports:
      - "8000:8000"
    networks:
      - project_network

networks:
  project_network:
